[package]
name = "rocksq"
version.workspace = true
edition.workspace = true
authors.workspace = true
description.workspace = true
homepage.workspace = true
repository.workspace = true
readme.workspace = true
keywords.workspace = true
categories.workspace = true
license.workspace = true
rust-version.workspace = true

[lib]
crate-type = ["cdylib", "lib"]

[dependencies]
queue_rs = { workspace = true }
pyo3 = { workspace = true }
rocksdb = { workspace = true }

[dev-dependencies]
serial_test = { workspace = true }

[build-dependencies]
pyo3-build-config = { workspace = true }
cbindgen = { workspace = true }

[package.metadata.maturin]
python-source = "python"

[features]
extension-module = ["pyo3/extension-module"]
default = ["extension-module"]

