class PersistentQueueWithCapacity:
    def __init__(self, path: str, max_elements: int = 1_000_000_000): ...

    def push(self, items: list[bytes], no_gil: bool = True): ...

    def pop(self, max_elements: int = 1, no_gil: bool = True) -> list[bytes]: ...

    @property
    def is_empty(self) -> bool: ...

    @property
    def disk_size(self) -> int: ...

    @property
    def payload_size(self) -> int: ...

    @property
    def len(self) -> int: ...